### ISSUE TITLE
Type-feature

### ISSUE THREAD

**Issue by ervinanoh** [hexmap/herdr-geojson#1]
The key-value "type":"feature" must be added into the Features values to avoid an invalid geojson error when rendering a map on geojson.io for example.

**Comment by kafitz** [comment]
Thanks for reaching out @ervinanoh! Commit ba6265bb508eb7fa5af8a37a893a85b19b8e4ee0 should address this.

This code was a quick demo for talking with Vincent about finding a common format for GPS data and it certainly could be better. If there's any more useful examples, I'd be happy to contribute towards that.
